### ISSUE TITLE
[MASWE-0017] Cryptographic Keys Not Properly Protected on Export

### ISSUE THREAD

**Issue by cpholguera** [OWASP/maswe#127]
## Description

Create a new risk for "Cryptographic Keys Not Properly Protected on Export (MASVS-CRYPTO-2)" using the following information:

Before exporting, keys should be "wrapped" or encrypted with another key. This process ensures that the cryptographic key is protected during and after export. This is true even if the key is sent over a secure channel.

Create "`risks/MASVS-CRYPTO/2-***-****/crypto-keys-not-protected-export/risk.md`" including the following content:

```yaml
---
title: Cryptographic Keys Not Properly Protected on Export
alias: crypto-keys-not-protected-export
platform: [android, ios]
profiles: [L2]
mappings:
  masvs-v2: [MASVS-CRYPTO-2, MASVS-STORAGE-1, MASVS-NETWORK-1]
  mastg-v1: []

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r5.pdf>
- <https://developer.android.com/reference/kotlin/android/security/keystore/KeyProtection>
- <https://developer.apple.com/documentation/cryptokit/aes/keywrap>
- <https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_as_data#2933723>

When creating the corresponding tests, use the following areas to guide you:

- key wrapping (NIST.SP.800-175Br1 5.3.5)

**MASTG v1 Refactoring:**

If the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.

## Acceptance Criteria

- [ ] The risk has been created in the correct directory (`risks/MASVS-CRYPTO/2-***-****/crypto-keys-not-protected-export/risk.md`)
- [ ] The risk content follows the [guidelines](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)
- [ ] At least one GitHub Issue has been created for the corresponding tests (derived from "Modes of Introduction")
- [ ] The risk indicates the related MASTG v1 tests in its metadata.
