### ISSUE TITLE
[MASWE-0003] Backup Unencrypted

### ISSUE THREAD

**Issue by cpholguera** [OWASP/maswe#141]
> This prev. open PR could contain useful inputs: https://github.com/OWASP/owasp-mastg/pull/2604/files#diff-a6472df266173afc665035280a844525ce81374d2b343070dfd37a24deffa541

## Description

Create a new risk for "Backup Unencrypted (MASVS-STORAGE-2)" using the following information:

The app may not encrypt sensitive data in backups, which may compromise data confidentiality.

Create "`risks/MASVS-STORAGE/2-***-****/backup-unencrypted/risk.md`" including the following content:

```yaml
---
title: Backup Unencrypted
alias: backup-unencrypted
platform: [android]
profiles: [L2]
mappings:
  masvs-v1: [MSTG-STORAGE-8]
  masvs-v2: [MASVS-STORAGE-2, MASVS-PRIVACY-1]
  mastg-v1: [MASTG-TEST-0058, MASTG-TEST-0009]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://developer.android.com/guide/topics/data/autobackup#define-device-conditions>

When creating the corresponding tests, use the following areas to guide you:

- Backup Device Conditions clientSideEncryption and deviceToDeviceTransfer Not Checked (Android)

**MASTG v1 Refactoring:**

If the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.

- [MASTG-TEST-0058 - Testing Backups for Sensitive Data (ios)](https://mas.owasp.org/MASTG/tests/android/MASVS-STORAGE/MASTG-TEST-0058/)
- [MASTG-TEST-0009 - Testing Backups for Sensitive Data (android)](https://mas.owasp.org/MASTG/tests/android/MASVS-STORAGE/MASTG-TEST-0009/)

## Acceptance Criteria

- [ ] The risk has been created in the correct directory (`risks/MASVS-STORAGE/2-***-****/backup-unencrypted/risk.md`)
- [ ] The risk content follows the [guidelines](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)
- [ ] At least one GitHub Issue has been created for the corresponding tests (derived from "Modes of Introduction")
- [ ] The risk indicates the related MASTG v1 tests in its metadata.
